{% set name = "profimp" %}
{% set version = "0.1.0" %}
{% set sha256 = "d18e0145e131092a5d467e3a04a9034064856dfd5e1860ed6354dd844c9e0d54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - profimp = profimp.main:main

requirements:
  host:
    - python
    - pbr
    - pip
  run:
    - python

test:
  commands:
    - profimp

about:
  home: http://boris-42.me/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python imports tracer'
  description: |
    Profimp allows you to trace imports of your code. This lib should be used
    to simplify optimization of imports in your code. At least you will find
    what consumes the most part of time and do the right decisions.
  dev_url: https://github.com/boris-42/profimp

extra:
  recipe-maintainers:
    - scopatz
