travis:
  secure:
    BINSTAR_TOKEN: qGWu9Pi+rdOh7PGPbCaznSJIySq6cj/UHd3fSpC32qWJ3yya08BKAAgn8AsXn/xfGeR7MjKo1aK4ihCr144XFeUQ04dNFzQnqyWP4aTJATc0Kf7UD89JdbWqDKeQhLQlnGygETUhESiBw9qpu7JJvJZvYrRdcY+6v+jZKq5cghRAqZ5Ul+AmxFOQw65Iwqg7MF8uzE+fOHQlX/5uArkOs290sKs2XNkdQwl6GP6bw6UnoNEC3sHkPkIM/YfWQJDdmOmOPwihGp1tJixbrtS9NAzQDqIFGc1j6zkxzyEvg4vU+LAZC8vOwGPw7AIylICBsZ/Euh0WBUptkPcW75B6BGpIPBvGbk29hTcs92tyiyvnfK/g4Go3zoJsNymo1UIRZoZeORgDpGM0YgTElm76u7xhZpPR364CwGbiYdido9gfm5LRd/d0lz+6UrvWIYz8ng60UuRKIdBOo7fbwjul2S5aQkWzJ6cLAIl2/iFAAJNT5YIVmOLqHJJ3XuEv1p+nDJMYXQZPfJRx9CqFn3f2VQTFB3sQAqdDzpGf2KXjP/6cr1JQqz9/+A+9oO9sUQ0WrtDuOC9tcPpCS4o4vQz7bnSCi9uyCGD7qb1VNQaiyfgQENsPu67gQDNs9cVx7emJ1KRS/ALNJMjbL1f6mbtfZ4JV8VY4C92eVlG5qTUvGiE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
