travis:
  secure:
    BINSTAR_TOKEN: Y6LX8K24qtYOloe3VxV9L3kYEwYh8dV1lpr7BQBq5GXJKoe1I9V7lVfX3tZ9dMgfsmH7FAyEJk/LVflDSf/vdG4eU35LEO64V+MMro+a44Zneu/sxhkSlH1V2hvHZBKpg75hACpaOUjOd12odtwtwn2OUhSmTh3/Kb/dLU+1ccg1oIBve0Nh1W4ihzmh7wZBDno9tmA8oSsjHHf6XHC0jOH2nPkmU1mlXdPaWyKoyyYRlLEAiN86E2BYAHT/1Yp9rwvI23Q+tVao2Y9rnO3JExAMbB6AKXwJNiZJFCOHEdtl/xOgV/8quISucuF2l+/e+XudFrD6Jf285V4UsFDnUs44YTarTQUJFhCqzLqPrOHSaLfMIHTAoCf8hI9nqds2a1UzTirBqnp2eowhFLZXm1eh4U2gl+ycw9BTzYtW1lEqg1Mab6nouY8v+L7grRLGl/hha817sfqjNjAagfHIRdyJwja6smfNwxqJ+74vhqUI8+3mLmkHKhcbeKDZNm+mMOi7yByI1cRHs8zgINi/ss6iB4ABHA5jlTu1nvAWwBH/NFN5byOqqaU7TigefuINgwbjjr2zFCxhhOMUl1Qw3/5kbYFCmGjxFaJWJ8ZinvsqL9BhMu2wpNbMwKYncaodh9NVpPwOX2uSi76ZvAogOaq5An+lu6JTBA9FEYPOCY8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
